services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/:/var/www
    depends_on:
      - php
      - db
    networks:
      - app
  php:
    build: ./backend
    working_dir: /var/www
    volumes:
      - ./backend/:/var/www
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app
    depends_on:
      - db
      - redis

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "33061:3306"
    networks:
      - app

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app
    volumes:
      - redis_data:/data

networks:
  app:
    driver: bridge

volumes:
  db_data:
  redis_data: